SUPABASE_URL = "https://ehpnpjsrghlyeqafzora.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVocG5wanNyZ2hseWVxYWx6b3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzEwMjcsImV4cCI6MjA3MDg0NzAyN30.VBFzs4xo9V_DuGwJel0slxB4-Ut8pmwsRKT5bgTlkNc"
SUPABASE_SERVICE_KEY = "[REDACTED:jwt-token]"
