# Copy this to your Streamlit Cloud app settings → Secrets
# Go to: https://share.streamlit.io/ → Your app → Settings → Secrets
# 
# SECURITY: Only using anon key - service key bypasses RLS and is a security risk

SUPABASE_URL = "https://ehpnpjsrghlyeqafzora.supabase.co" 
SUPABASE_ANON_KEY = "your_anon_key_here"

# Note: SERVICE_KEY removed for security - not needed in interactive apps
# Service keys bypass Row Level Security and are risky if they leak
