# Copy this to your Streamlit Cloud app settings → Secrets
# Go to: https://share.streamlit.io/ → Your app → Settings → Secrets

SUPABASE_URL = "https://ehpnpjsrghlyeqafzora.supabase.co"
SUPABASE_ANON_KEY = "[REDACTED:jwt-token]"
SUPABASE_SERVICE_KEY = "[REDACTED:jwt-token]"
