title: Python Full Course for Beginners (9h)
provider: YouTube
level: Beginner
start_date: '2025-02-01'
duration: 9 hours
url: https://example.com/python-9h
status: in-progress
tags:
- python
- video
