[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "miguel_toolbox"
version = "0.0.1"
description = "Reusable logic library"
authors = [{ name="Miguel Gonzalez" }]
requires-python = ">=3.10"
